# server.py
# SuicideSelfHarmDetector XenForo classifier API
#
# This adapter is designed for the final Linear SVM artefact produced by
# training12_py314.py. The model was trained at sentence level, so full
# XenForo messages are split into sentences, classified, and then aggregated.
#
# Expected model artefact (preferred):
#   Suicide_SVM_pipeline.joblib
#
# The pipeline contains:
#   CountVectorizer -> TfidfTransformer -> LinearSVC
# and accepts raw strings directly via pipeline.predict(list_of_sentences).

from __future__ import annotations

import hmac
import math
import os
import re
import traceback
from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence, Tuple

import joblib
from flask import Flask, jsonify, request


# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

HERE = Path(__file__).resolve().parent
DEFAULT_MODEL_PATH = HERE / "models" / "Suicide_SVM_pipeline.joblib"
MODEL_PATH = Path(os.environ.get("MHFS_MODEL_PATH", str(DEFAULT_MODEL_PATH))).expanduser().resolve()

API_KEY = os.environ.get("MHFS_API_KEY", "")
HOST = os.environ.get("MHFS_HOST", "127.0.0.1")
PORT = int(os.environ.get("MHFS_PORT", "8000"))
MAX_MESSAGE_CHARS = int(os.environ.get("MHFS_MAX_MESSAGE_CHARS", "50000"))

# The final LinearSVC does not expose calibrated probabilities. We therefore
# report a softmax-normalised decision-function score as a display/ranking
# proxy only. Moderation recommendations below are label-driven, not threshold-
# driven, so this uncalibrated score is not used as a clinical probability.
SCORE_TYPE = "linear_svc_decision_softmax_proxy"

SAFE_LABEL = "not_harmful"
IDEATION_LABEL = "ideation"
METHOD_LABEL = "method_or_action"

# Higher number = more moderation-critical when aggregating sentence results.
LABEL_PRIORITY = {
    SAFE_LABEL: 0,
    IDEATION_LABEL: 1,
    METHOD_LABEL: 2,
}


# -----------------------------------------------------------------------------
# Model loading
# -----------------------------------------------------------------------------

app = Flask(__name__)


def _load_model(path: Path):
    if not path.exists():
        raise FileNotFoundError(
            f"SVM model not found: {path}. Set MHFS_MODEL_PATH to the final "
            "Suicide_SVM_pipeline.joblib generated by training12_py314.py."
        )

    loaded = joblib.load(path)

    # Preferred artefact: complete sklearn Pipeline.
    if hasattr(loaded, "predict"):
        return {"kind": "pipeline", "pipeline": loaded}

    # Also support the audit/reuse bundle written by training12_py314.py.
    if isinstance(loaded, dict):
        required = {"model", "count_vectorizer", "tfidf_transformer"}
        if required.issubset(loaded):
            return {
                "kind": "bundle",
                "model": loaded["model"],
                "count_vectorizer": loaded["count_vectorizer"],
                "tfidf_transformer": loaded["tfidf_transformer"],
                "classes": loaded.get("classes"),
            }

    raise TypeError(
        "Unsupported model artefact. Expected the complete SVM sklearn Pipeline "
        "or the SVM bundle produced by training12_py314.py."
    )


print(f"[INFO] Loading SVM model from: {MODEL_PATH}")
MODEL = _load_model(MODEL_PATH)
print(f"[INFO] Model loaded successfully ({MODEL['kind']}).")


# -----------------------------------------------------------------------------
# Text and prediction helpers
# -----------------------------------------------------------------------------

# Lightweight splitter which keeps source offsets. Newlines terminate a
# sentence; punctuation followed by whitespace/end also terminates a sentence.
_SENTENCE_RE = re.compile(r"\S(?:.*?\S)?(?:[.!?]+(?=\s+|$)|(?=\n+)|$)", re.DOTALL)


def check_api_key() -> bool:
    if not API_KEY:
        return True

    auth_header = request.headers.get("Authorization", "")
    expected = f"Bearer {API_KEY}"
    return hmac.compare_digest(auth_header, expected)


def extract_message(payload: Dict[str, Any]) -> str:
    message = payload.get("message", "")
    if message is None:
        return ""
    return str(message).strip()


def split_sentences(message: str) -> List[Dict[str, Any]]:
    results: List[Dict[str, Any]] = []

    for match in _SENTENCE_RE.finditer(message):
        raw = match.group(0)
        leading = len(raw) - len(raw.lstrip())
        trailing = len(raw) - len(raw.rstrip())
        text = raw.strip()
        if not text:
            continue

        start = match.start() + leading
        end = match.end() - trailing
        results.append({"text": text, "start_offset": start, "end_offset": end})

    # Defensive fallback for unusual punctuation/Unicode input.
    if not results and message.strip():
        stripped = message.strip()
        start = message.find(stripped)
        results.append({
            "text": stripped,
            "start_offset": max(start, 0),
            "end_offset": max(start, 0) + len(stripped),
        })

    return results


def normalise_label(raw_label: Any) -> str:
    label = str(raw_label).strip().lower()

    # Match known safe labels before looking for harmful-label keywords. The
    # publication-facing safe wording contains all three words "ideation",
    # "method" and "action", so keyword-first matching would invert it into a
    # Method/action result.
    if (
        label in {
            "not suicide post",
            "not ideation or method or action",
            "not_harmful",
            "not harmful",
            "safe",
            "none",
        }
        or "not suicide" in label
    ):
        return SAFE_LABEL
    if "method" in label or "action" in label:
        return METHOD_LABEL
    if "ideation" in label:
        return IDEATION_LABEL

    # Unknown labels are intentionally preserved rather than silently mapped
    # to safe. The aggregation policy below treats them conservatively.
    return label.replace(" ", "_")


def _classes_for_model() -> List[str]:
    if MODEL["kind"] == "pipeline":
        pipeline = MODEL["pipeline"]
        classes = getattr(pipeline, "classes_", None)
        if classes is None and hasattr(pipeline, "named_steps"):
            final = pipeline.named_steps.get("svm")
            classes = getattr(final, "classes_", None)
    else:
        classes = MODEL.get("classes")
        if classes is None:
            classes = getattr(MODEL["model"], "classes_", None)

    return [str(value) for value in list(classes)] if classes is not None else []


def _predict_raw(texts: Sequence[str]) -> Tuple[List[Any], Any]:
    if MODEL["kind"] == "pipeline":
        pipeline = MODEL["pipeline"]
        predictions = list(pipeline.predict(list(texts)))
        decision = pipeline.decision_function(list(texts)) if hasattr(pipeline, "decision_function") else None
        return predictions, decision

    vectorizer = MODEL["count_vectorizer"]
    transformer = MODEL["tfidf_transformer"]
    classifier = MODEL["model"]

    counts = vectorizer.transform(list(texts))
    tfidf = transformer.transform(counts)
    predictions = list(classifier.predict(tfidf))
    decision = classifier.decision_function(tfidf) if hasattr(classifier, "decision_function") else None
    return predictions, decision


def _as_rows(values: Any, row_count: int) -> List[List[float]]:
    if values is None:
        return [[] for _ in range(row_count)]

    if hasattr(values, "tolist"):
        values = values.tolist()

    if row_count == 1 and isinstance(values, list) and values and not isinstance(values[0], list):
        return [[float(v) for v in values]]

    if isinstance(values, list):
        rows: List[List[float]] = []
        for row in values:
            if isinstance(row, list):
                rows.append([float(v) for v in row])
            else:
                rows.append([float(row)])
        return rows

    return [[] for _ in range(row_count)]


def _softmax_score(decision_row: Sequence[float], predicted_raw: Any, classes: Sequence[str]) -> float:
    if not decision_row:
        return 0.0

    # Multiclass LinearSVC: one decision value per class.
    if len(decision_row) == len(classes) and len(classes) > 1:
        maximum = max(decision_row)
        exps = [math.exp(value - maximum) for value in decision_row]
        denominator = sum(exps) or 1.0
        try:
            index = list(classes).index(str(predicted_raw))
        except ValueError:
            index = max(range(len(decision_row)), key=lambda i: decision_row[i])
        return round((exps[index] / denominator) * 100.0, 2)

    # Binary fallback: convert the single margin to a two-way logistic proxy.
    margin = float(decision_row[0])
    probability_positive = 1.0 / (1.0 + math.exp(-max(min(margin, 50.0), -50.0)))
    if len(classes) == 2 and str(predicted_raw) == str(classes[0]):
        probability_positive = 1.0 - probability_positive
    return round(probability_positive * 100.0, 2)


def predict_sentences(sentences: Sequence[Dict[str, Any]]) -> List[Dict[str, Any]]:
    texts = [str(item["text"]) for item in sentences]
    raw_predictions, decision_values = _predict_raw(texts)
    classes = _classes_for_model()
    decision_rows = _as_rows(decision_values, len(texts))

    results: List[Dict[str, Any]] = []
    for index, (sentence, raw_prediction) in enumerate(zip(sentences, raw_predictions)):
        label = normalise_label(raw_prediction)
        score = _softmax_score(
            decision_rows[index] if index < len(decision_rows) else [],
            raw_prediction,
            classes,
        )
        results.append({
            "text": sentence["text"],
            "label": label,
            "raw_label": str(raw_prediction),
            "score": score,
            "score_type": SCORE_TYPE,
            "start_offset": int(sentence["start_offset"]),
            "end_offset": int(sentence["end_offset"]),
        })

    return results


def aggregate_results(sentence_results: Sequence[Dict[str, Any]]) -> Dict[str, Any]:
    if not sentence_results:
        return {
            "risk_level": "none",
            "recommended_action": "allow",
            "highest_label": SAFE_LABEL,
            "highest_score": 0.0,
            "score_type": SCORE_TYPE,
            "flagged_parts": [],
            "sentence_results": [],
        }

    def rank(item: Dict[str, Any]) -> Tuple[int, float]:
        label = str(item.get("label", ""))
        # Unknown labels rank above safe so unexpected model outputs do not
        # silently become an allow decision.
        priority = LABEL_PRIORITY.get(label, 1)
        return priority, float(item.get("score", 0.0))

    highest = max(sentence_results, key=rank)
    highest_label = str(highest.get("label", ""))
    highest_score = float(highest.get("score", 0.0))

    if highest_label == SAFE_LABEL:
        risk_level = "none"
        action = "allow"
    elif highest_label == METHOD_LABEL:
        risk_level = "high"
        action = "moderate"
    elif highest_label == IDEATION_LABEL:
        risk_level = "medium"
        action = "moderate"
    else:
        risk_level = "unknown"
        action = "moderate"

    flagged = [item for item in sentence_results if item.get("label") != SAFE_LABEL]

    return {
        "risk_level": risk_level,
        "recommended_action": action,
        "highest_label": highest_label,
        "highest_score": round(highest_score, 2),
        "score_type": SCORE_TYPE,
        "flagged_parts": flagged,
        "sentence_results": list(sentence_results),
    }


def classify_payload(payload: Dict[str, Any]) -> Dict[str, Any]:
    message = extract_message(payload)

    if not message:
        return {
            "risk_level": "none",
            "recommended_action": "allow",
            "highest_label": SAFE_LABEL,
            "highest_score": 0.0,
            "score_type": SCORE_TYPE,
            "flagged_parts": [],
            "sentence_results": [],
            "error": "Empty message.",
        }

    if len(message) > MAX_MESSAGE_CHARS:
        raise ValueError(f"Message exceeds maximum length of {MAX_MESSAGE_CHARS} characters.")

    sentences = split_sentences(message)
    sentence_results = predict_sentences(sentences)
    return aggregate_results(sentence_results)


# -----------------------------------------------------------------------------
# Routes
# -----------------------------------------------------------------------------

@app.route("/", methods=["GET"])
def index():
    return jsonify({
        "service": "SuicideSelfHarmDetector classifier API",
        "status": "running",
        "model": "Linear SVM",
        "model_kind": MODEL["kind"],
        "score_type": SCORE_TYPE,
    })


@app.route("/health", methods=["GET"])
def health():
    return jsonify({
        "ok": True,
        "model_loaded": True,
        "model": "Linear SVM",
        "model_kind": MODEL["kind"],
    })


@app.route("/api/classify", methods=["POST"])
@app.route("/", methods=["POST"])
def classify():
    if not check_api_key():
        return jsonify({
            "risk_level": "unknown",
            "recommended_action": "moderate",
            "highest_label": "",
            "highest_score": 0,
            "flagged_parts": [],
            "error": "Unauthorized request.",
        }), 401

    try:
        payload = request.get_json(silent=True)
        if not isinstance(payload, dict):
            return jsonify({
                "risk_level": "unknown",
                "recommended_action": "moderate",
                "highest_label": "",
                "highest_score": 0,
                "flagged_parts": [],
                "error": "Invalid JSON payload.",
            }), 400

        return jsonify(classify_payload(payload)), 200

    except ValueError as exc:
        return jsonify({
            "risk_level": "unknown",
            "recommended_action": "moderate",
            "highest_label": "",
            "highest_score": 0,
            "flagged_parts": [],
            "error": str(exc),
        }), 400
    except Exception as exc:
        traceback.print_exc()
        return jsonify({
            "risk_level": "unknown",
            "recommended_action": "moderate",
            "highest_label": "",
            "highest_score": 0,
            "flagged_parts": [],
            "error": str(exc),
        }), 500


if __name__ == "__main__":
    app.run(debug=False, host=HOST, port=PORT)
